"""empty message

Revision ID: 776c628b65a7
Revises: 
Create Date: 2022-05-22 16:18:33.764469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776c628b65a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###
